project:
  type: website
  output-dir: docs

website:
  title: "Hamish Dickson"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/hamishdickson/
      - icon: github
        href: https://github.com/hamishdickson
      - icon: twitter
        href: https://twitter.com/_mishy
format:
  html:
    theme: cosmo
    css: styles.css



